Signature ellipsis for transaction history
solana-labs/solana pull request #15979
Opened 2021-03-18 07:43 UTC by Arrowana

#### Problem
Horizontal scrollbar on history looks horrible

#### Summary of Changes
Trying out some stuff to make it look like this

![image](https://user-images.githubusercontent.com/8245419/111589826-7a290280-8819-11eb-9fc1-ec0d0d5ef5ae.png)

Who reads the full signature anyway?

I imagine we would even truncate more of it on small media, as we still want to be able to browse without a horizontal scrollbar

I can't quite get how to do that cleanly though

Fixes #14975

2021-03-18 17:29 UTC, oJshua commented
I believe we do truncate most transaction signatures on smaller media, but I fully agree this could be handled better altogether. Scrolling isn't so horrible on a touch screen, but on a desktop you might have to find the scrollbar at the bottom of the component.

We do have a similar ticket: https://github.com/solana-labs/solana/issues/14975

@Arrowana thanks for you efforts here. We can keep spinning on it. I'll close for now since we're already tracking, but please feel free to resubmit a PR if you come up with a solution.

2021-03-18 17:32 UTC, oJshua commented
We do have this snippet of SCSS too if you wanted to expand on it:
https://github.com/solana-labs/solana/blob/master/explorer/src/scss/_solana.scss#L205-L227

Address components have a truncate parameter.

2021-03-18 17:42 UTC, oJshua requested changes
Comments in main thread.

2021-03-18 18:25 UTC, oJshua commented on explorer/src/scss/_solana.scss
> +td {
We should avoid having a global rule for table columns. See the snippet I posted.

2021-03-18 21:12 UTC, Arrowana commented
> We do have this snippet of SCSS too if you wanted to expand on it:
> https://github.com/solana-labs/solana/blob/master/explorer/src/scss/_solana.scss#L205-L227
> 
> Address/Signature components have a truncate parameter.

Yes, but it doesn't seem to kick in because the parent container is `table-responsive`, i passed `truncate` to Signature but it was still not truncated. I will try this force-truncate that i missed though.

Agree that this draft was a hack, I just presented that to show how it could look. I will investigate how to achieve it properly

2021-03-30 07:33 UTC, oJshua commented
You're right about it not kicking in without it hitting that media query! I've been trying out a different truncation method as seen in the screenshot below. Let me know if you have any thoughts. Thanks again @Arrowana! Feel free to reopen this or submit a new PR if you come up with anything else.

![001_mint_transfers](https://user-images.githubusercontent.com/188792/112950410-1b079f80-90ef-11eb-9b94-0f7a29b5cfd8.png)

2021-03-30 07:33 UTC, closed without merging