add getMultipleAccountsInfo which uses the getMultipleAccounts RPC method
solana-labs/solana pull request #18736
Opened 2021-07-16 22:55 UTC by tomjohn1028

#### Problem
Web3.js is missing the [`getMultipleAccounts`](https://docs.solana.com/developing/clients/jsonrpc-api#getmultipleaccounts) RPC method

#### Summary of Changes
Add `getMultipleAccountsInfo` to the Connection class

Fixes #

2021-07-19 18:04 UTC, oJshua requested changes
Thanks for adding this! Just one minor change and would you mind adding a quick test?

2021-07-19 18:04 UTC, oJshua commented on web3.js/src/connection.ts
> +    try {
This outer try block isn't necessary. (based on convention established by other calls and redundant throw if 'error' exists in res)

2021-07-19 19:13 UTC, tomjohn1028 commented
@oJshua I made the requested changes, but it seems the `npm run test:live` command fails. I'm not up to speed on the different test commands/environments. Care to help me bring this home? Or provide some more context so I can understand what's missing?

2021-07-20 02:40 UTC, oJshua commented
Thanks @tomjohn1028 for your effort on this. I simply added a couple airdrops using the helpers.

2021-07-20 02:41 UTC, oJshua approved these changes

2021-07-20 16:42 UTC, merged