move package_snapshots to AccountsPackagePre ctors
solana-labs/solana pull request #18997
Opened 2021-07-30 17:51 UTC by snOm3ad

#### Problem
The functions `snapshot_utils::package_xxx_snapshot` have minimal functionality that could
easily moved into constructors inside `snapshot_package::AccountsPackagePre` thereby 
offloading the `snapshot_utils.rs` which is already pretty big.

More info [here](https://github.com/solana-labs/solana/pull/18504#discussion_r673756619).

#### Summary of Changes
I had to make the snapshot prefix constants inside `snapshot_utils.rs` public at the crate level 
in order to make this work. I'm not sure whether or not introducing this dependency is entirely 
good, either way the `snapshot_utils.rs` file needs a lot of rework so things will move around, 
I believe this does the work in the meantime. Any feedback will be greatly appreciated.

Fixes #18815

2021-08-02 22:03 UTC, brooksprumo requested changes
Overall looks good! Thanks for picking up this issue. After you make the changes, request a re-review from me.

2021-08-03 01:08 UTC, brooksprumo requested changes
I think just one small change.

2021-08-03 01:08 UTC, brooksprumo commented on runtime/src/snapshot_package.rs
> +    fn new_snapshot<P>(
Looks like this was missed. Please make this one new_snapshot_package.

2021-08-03 14:28 UTC, brooksprumo commented
@carllin I reviewed this and it looks good to me. Since this issue and PR is originally from [your comment here](https://github.com/solana-labs/solana/pull/18504#discussion_r673756619), can you double check to make sure it meets your expectations?

Thanks!

2021-08-04 06:23 UTC, carllin commented
Looks great, thanks guys for taking this! 😃

2021-08-04 06:23 UTC, carllin approved these changes

2021-08-04 14:02 UTC, brooksprumo approved these changes

2021-08-04 14:03 UTC, merged

2021-08-04 14:03 UTC, brooksprumo commented
Thanks for your work here, @snOm3ad!

2021-08-04 14:05 UTC, snOm3ad commented
> Thanks for your work here, @snOm3ad!

No problem👍I hope to contribute more in the future!