Check file size of `snapshot_version` when unarchiving snapshot
solana-labs/solana pull request #21925
Opened 2021-12-15 16:11 UTC by mooori

#### Problem

The size of the `snapshot_version` file is not checked, which is an attack vector. See #18504, #18841. 

#### Summary of Changes

Check the size of the file containing the `snapshot_version` before opening it. If the size exceeds `MAX_SNAPSHOT_VERSION_FILE_SIZE`, an error is returned and the file will not be opened.

#### Notes

- `MAX_SNAPSHOT_VERSION_FILE_SIZE` was chosen arbitrarily - let me know if another value makes more sense.
- If the file size is too big, an error is created and returned according to other code in `snapshot_utils` dealing with files that are too big (namely `create_snapshot_data_file_stream`).

#### Test

So far, there is no dedicated test for `unarchive_snapshot`. Setting up such a test just to verify the `snapshot_version` file size is checked correctly looks like overkill.

Fixes #18841

2021-12-15 16:40 UTC, mvines commented
Oh nice. This PR lgtm but @brooksprumo can you please take a look as well for a full review

2021-12-15 16:44 UTC, brooksprumo commented
@mooori Thank you for your submission! Please mark the PR as "Ready for review" when you feel it's completed and I will take a look.

2021-12-15 17:13 UTC, mooori commented
@brooksprumo CI checks haven't finished yet, but since it's just a small PR I think it's good to go (status is updated).

If there should be any issues, I'll be back later. I ran `cargo test`, `cargo fmt` and `cargo clippy` locally inside `runtime` and they didn't complain.

2021-12-15 18:46 UTC, brooksprumo requested changes
Overall looks good! I'm requesting some small tweaks.

Also:
> So far, there is no dedicated test for unarchive_snapshot. Setting up such a test just to verify the snapshot_version file size is checked correctly looks like overkill.

I'd like tests for the file-to-snapshot-version function (see comments below). Those tests do not necessarily need to be part of this PR though. If you'd rather not add the tests here, please create a new issue name something like "Add tests for snapshot_version_from_file" and mark it as "good first issue".

I'd like two tests:

1. Ensure that a version file with the default `SnapshotVersion` passes
2. Ensure that a version file with a size `MAX_SNAPSHOT_VERSION_FILE_SIZE + 1` fails

2021-12-15 18:46 UTC, brooksprumo commented on runtime/src/snapshot_utils.rs
> +        // Read snapshot_version from file.
Please move this into its own function (and all the way down to line 986, the end of this block, but I cannot select that far in GitHub...).

Named something like `snapshot_version_from_file()` and have it take an `impl AsRef<Path>` and return `Result<String>`.

2021-12-15 18:46 UTC, brooksprumo commented on runtime/src/snapshot_utils.rs
> +const MAX_SNAPSHOT_VERSION_FILE_SIZE: u64 = 128; // byte
I'd prefer this constant to be smaller. Since the version is only 5 bytes now, I propose this value be set to 8.

2021-12-15 18:48 UTC, brooksprumo commented
Oh, also please re-request a review from me once the changes are made. This way I'll make sure to see the review request in my GH dashboard.

2021-12-16 18:02 UTC, mooori commented
Thank you for the review @brooksprumo. The suggestions have been implemented (including tests).

2021-12-16 18:41 UTC, brooksprumo requested changes
I like it! Two more small things and then I think it'll be all set!

2021-12-16 18:41 UTC, brooksprumo commented on runtime/src/snapshot_utils.rs
> +// threshold, it is not opened and an error is returned.
Minor: Please make these doc comments (use three slashes: `///`).

2021-12-16 18:41 UTC, brooksprumo commented on runtime/src/snapshot_utils.rs
> +        usize::try_from(MAX_SNAPSHOT_VERSION_FILE_SIZE + 1).unwrap();
Capture this as a variable and use it for the size in the `file_content` array below.

2021-12-17 15:51 UTC, brooksprumo approved these changes
Looks good! Thanks again for your submission, @mooori!

2021-12-17 18:27 UTC, merged

2021-12-17 20:28 UTC, brooksprumo commented
@Mergifyio backport v1.8