13295 explorer: use anchor links for subsections
solana-labs/solana pull request #23151
Opened 2022-02-15 19:17 UTC by KitanGarcia

#### Problem    
Explorer subsections did not have anchors attached to them for easy navigation

#### Summary of Changes    
* Added anchors linking to the subsections/headers throughout Explorer

Fixes #13295

2022-03-09 21:27 UTC, oJshua commented
@KitanGarcia this isn't working as intended, for example when I visit [http://localhost:3000/address/SysvarC1ock11111111111111111111111111111111#history](url) the browser should scroll down to the Transaction History subsection.

2022-03-28 01:04 UTC, KitanGarcia commented
> @KitanGarcia this isn't working as intended, for example when I visit [http://localhost:3000/address/SysvarC1ock11111111111111111111111111111111#history](url) the browser should scroll down to the Transaction History subsection.

Thanks for reviewing and getting back to me! I have an idea on how to do and I'll hope to get to it soon. Apologies for such a late reply!

2022-03-31 01:50 UTC, KitanGarcia commented
> @KitanGarcia this isn't working as intended, for example when I visit [http://localhost:3000/address/SysvarC1ock11111111111111111111111111111111#history](url) the browser should scroll down to the Transaction History subsection.

Hi @oJshua , I have a couple ideas on how to do this. Since the reason it isn't working as expected is due to different components rendering at different times, I see 2 approaches:
1) Using Refs and scrolling to them in a useEffect after X seconds.    
```
  useEffect(() => {
    if (hashRef && hashRef.current) {
      setTimeout(function () {
        hashRef!.current!.scrollIntoView();
      }, 3000);
    }
  }, [hashRef]);

  return (
    <div className="card">
      <div className="card-header">
        <h4 id="txStats" className="card-header-title">
          <a href="#txStats" ref={hashRef}>
            Live Transaction Stats
          </a>
        </h4>
      </div>
      <TpsCardBody />
    </div>
  );
```
This works (at least for most), but is not so nice, since it would have to wait and it may not work for those with poor connection speeds.    

2) Creating skeletons for components that would be the same height and width as the component they represent so that the anchor element would not move out of focus when all components have finished rendering. This is probably cleaner, but would probably take a long time to build out.

Would you have a preference between these methods, or an alternative?

2022-04-20 18:44 UTC, KitanGarcia commented
@oJshua Just thought I'd ask once more if you'd have a preference or alternative solution regarding my above post: https://github.com/solana-labs/solana/pull/23151#issuecomment-1083976236

2022-05-05 06:33 UTC, jstarry commented
@steveluscher is this PR obsoleted by your recent changes?

2022-05-05 21:36 UTC, steveluscher requested changes
If you want to update this PR to treat these interesting sections as scroll anchors using the new `useScrollAnchor()` infra, please do and I'll accept it.

2022-05-05 21:36 UTC, steveluscher commented on explorer/src/components/SupplyCard.tsx
> +            <a href="#overview">Supply Overview</a>
I made a new bulletproof system for scrolling to anchors! Check it out in
#24861.

2022-05-05 21:38 UTC, steveluscher commented on explorer/src/components/SupplyCard.tsx
> +            <a href="#overview">Supply Overview</a>
Essentially it's this:

```
import { useScrollAnchor } from "providers/scroll-anchor";
/* ... */
const scrollAnchorRef = useScrollAnchor('overview');
/* ... */
<h4 className="card-header-title" ref={scrollAnchorRef}>
  Supply Overview
</h4>
```

2022-06-12 23:25 UTC, steveluscher commented
Feel free to reopen this if you'd like to take a second crack at it with the new API!

2022-06-12 23:25 UTC, closed without merging