The `signature` of a transaction should not be required for `sendAndConfirmRawTransaction`
solana-labs/solana pull request #28370
Opened 2022-10-12 22:03 UTC by jnwng

#### Problem
`sendAndConfirmRawTransaction` requires passing the `signature` of the transaction for confirmation, but since we haven't sent the transaction yet we don't have a valid transaction signature to confirm! See [this Typescript playground](https://www.typescriptlang.org/play?ssl=7&ssc=109&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgZwKYDsAmBBLBhCdAM2ChACUBDAdwBUpL1lKBjGYQgGjgPXVTYd03eo2aCucFgBsArshioo2MMACqUaXAC+cIlAgg4AcgACyCNMaUA9NVQAjAMwA6AFbJjAbgBQPloQKUoT8EuhwALxw-NQ8IQLshAAUMvKKyqoa0knGIJTAfKgwALQORZTGAJSVvgFM8DAMTKyJ4VExcKLNYUk1-oHwSA7SECwA1gAWlMgT3FYKAGqU0sCYAEIj4wASqMAA5hPwulE0+fB1oa0ue0UAMpSKChujk9MTvb4+p8DwaFi4mF4JDIVDoTXErRS8TC3EaYhaQhcaCgwGWwAAXqhetwhptXjM5tMYEsVus8Tt9ocdJU-EA) that exemplifies the issue.

`sendAndConfirmRawTransaction`'s third parameter is `confirmationStrategyOrConfirmOptions`, where `confirmationStrategy` is https://github.com/solana-labs/solana/blob/8036f6f3046b18795e6b7fab834b405c32295c1d/web3.js/src/connection.ts#L308-L310

this makes sense in the context of "confirming" a transaction, but not in the context of sending the transaction. in the case that `{ lastValidBlockHeight, blockhash }` is passed to `sendAndConfirmRawTransaction`, the signature of the sent transaction isn't actually being passed to `connection.confirmTransaction`: https://github.com/solana-labs/solana/blob/8036f6f3046b18795e6b7fab834b405c32295c1d/web3.js/src/utils/send-and-confirm-raw-transaction.ts#L74-L82

#### Summary of Changes

- Omits the requirement to pass `signature` to the `confirmationStrategy` for `sendAndConfirmRawTransaction`
- Passes the transaction signature from the sent transaction to wait for it to be confirmed

**Should result in the following to be valid:**
```TypeScript
const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash();
await sendAndConfirmRawTransaction(connection, transaction.serialize(), { blockhash, lastValidBlockHeight })
```

2022-10-12 22:07 UTC, jordansexton approved these changes
Change looks sensible to me!

2022-11-28 20:06 UTC, steveluscher requested changes
Oh wow. Good catch. Clearly nobody is using this, because it was born broken!

I'm pretty sure you have to update the upstream method signature to make this work nicely with Typescript:

```
export async function sendAndConfirmRawTransaction(
  connection: Connection,
  rawTransaction: Buffer,
  confirmationStrategy: BlockheightBasedTransactionConfirmationStrategy, // <--- this one
  options?: ConfirmOptions,
): Promise<TransactionSignature>;
```

2023-01-06 08:06 UTC, closed without merging

2023-01-30 04:06 UTC, steveluscher commented
Want to revive this, @jnwng?

2023-02-02 17:43 UTC, jnwng commented
yessir, i want to revive this! expect to be able to get to this next week

On Sun, Jan 29, 2023 at 11:06 PM, Steven Luscher < ***@***.*** > wrote:

> 
> 
> 
> Want to revive this, @ jnwng ( https://github.com/jnwng ) ?
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub (
> https://github.com/solana-labs/solana/pull/28370#issuecomment-1407963262 )
> , or unsubscribe (
> https://github.com/notifications/unsubscribe-auth/AAIRCRTWWS6G2PBBNJUXACTWU444TANCNFSM6AAAAAARDWISS4
> ).
> You are receiving this because you were mentioned. Message ID: <solana-labs/solana/pull/28370/c1407963262
> @ github. com>
> 
> 
>