Rename remaining ones to replay_vote_{sender,receiver}
solana-labs/solana pull request #29716
Opened 2023-01-15 13:20 UTC by ryoqun

(no rush; no need to work on weekend)

#### Problem

There's remaining instances of stale variable names for the type of `ReplayVote{Sender/Receiver}`.

Namely, I want to use `gossip_vote_sender` in #29196, but it's currently squatted by the stale variables here and there.

#### Summary of Changes

Rename 'em all with this  preparatory pr to ease review of #29196.

Fixes #

2023-01-15 19:29 UTC, carllin commented
ick yeah I made a mess here with the naming.

So both from `ReplayStage` and `BankingStage` the votes are being sent to `ClusterInfoVoteListener`. 

I named the type `ReplayVoteSender` because these votes were originally only being sent from `ReplayStage`. Maybe it's clearer to rename the type to `GossipVoteSender` because the target is `ClusterInfoVoteListener`.

2023-01-17 12:59 UTC, ryoqun commented
> Maybe it's clearer to rename the type to `GossipVoteSender` because the target is `ClusterInfoVoteListener`.

Okay, I'll revisit this whole rename after banking tracer. Firstly, I want to merge the tracer to be backported.

2023-01-17 16:35 UTC, apfitzge requested changes
Typos should be fixed, but otherwise looks good to me.

Fine to re-evaluate the naming at a later point, but making it consistent with the typename makes things more clear immediately imo.

2023-01-18 02:36 UTC, ryoqun commented on core/src/banking_stage.rs
> +            let (replay_vote_sender, _repaly_vote_receiver) = unbounded();
ugh, thanks for checking my sanity...: https://github.com/solana-labs/solana/pull/29716/commits/631144c0ecdae0a8c2da5c5fec96b8770d4c2ba1 ;)

2023-01-18 05:14 UTC, merged