reverse duplicate instance check to shutdown newer instance
solana-labs/solana pull request #30880
Opened 2023-03-23 22:01 UTC by jbiseda

#### Problem
Duplicate instance check will terminate the older node. The _newer_ node should be terminated as it is more likely to have operator engagement and terminating the older node could lead to a restart cycle between duplicate nodes if they are using auto-restart with systemd.

#### Summary of Changes
Shutdown newer node when duplicate instance is detected.

Fixes #

2023-03-23 22:19 UTC, steviez reviewed
We should update (maybe remove) this comment too:
https://github.com/solana-labs/solana/blob/653083806f7c9648153a6a060e715a2478c300ff/gossip/src/cluster_info.rs#L2415-L2421

I'm kind of leaning remove, one less place for things to get out of date.

2023-03-23 23:34 UTC, steviez commented
Looks like we have a unit test for this that needs to be updated as well
```
crds_value::test::test_check_duplicate_instance
```

2023-03-24 01:16 UTC, steviez approved these changes

2023-03-24 01:25 UTC, t-nelson approved these changes
:shipit: 

cc/ @sakridge

2023-03-24 02:08 UTC, steviez commented
Another CI failure that looks like it will require attention; see this in logs:
```
[2023-03-24T01:23:32.198305201Z ERROR solana_gossip::cluster_info] duplicate running instances of the same validator node: 6DsMmZ4mdArtj1HKzCmpjtwpHAnKZh11cgJNMPAyA7f7
```

2023-03-24 04:01 UTC, t-nelson commented
> Another CI failure that looks like it will require attention; see this in logs:
> 
> ```
> [2023-03-24T01:23:32.198305201Z ERROR solana_gossip::cluster_info] duplicate running instances of the same validator node: 6DsMmZ4mdArtj1HKzCmpjtwpHAnKZh11cgJNMPAyA7f7
> ```

weird one.  all of the nodes in that test have different gossip identities. :thinking:

2023-03-24 11:44 UTC, behzadnouri requested changes
The original order is intentional and the correct order. For example:

* If I restart my node and my node is staked, I will receive my old `NodeInstance` from gossip with an older timestamp. If we kill the newer instance there is no way to restart the node.
* If I hotswap my node, the new instance will receive/have `NodeInstance` from the older node through gossip, and again, if we kill the newer instance, hotswap will break.

2023-03-24 11:49 UTC, jbiseda commented
> The original order is intentional and the correct order. For example:

Thanks for clarifying. I think this might be worth a comment in the code.

2023-03-24 21:44 UTC, closed without merging