ci: run stable tests partially
solana-labs/solana pull request #31151
Opened 2023-04-11 18:36 UTC by yihau

#### Problem

#### Summary of Changes

Fixes #

2023-04-13 07:34 UTC, yihau commented
the latest build. if we have sufficient agents, it will only take 8 mins to build 😈 
<img width="1149" alt="Screenshot 2023-04-13 at 3 33 08 PM" src="https://user-images.githubusercontent.com/8209234/231687053-04c7316d-3ade-46c7-8439-706dee2a70a8.png">

2023-04-14 05:42 UTC, t-nelson requested changes
can you factor out the refactor/cleanup changes to a separate PR so the partitioning changes are better isolated?

2023-04-14 12:09 UTC, yihau commented
sure! I extracted some cleanup logic to PR 31196. I will rebase this PR when the PR 31196 merge.

2023-04-19 16:45 UTC, t-nelson commented
is this ready for another review pass?

2023-04-19 16:53 UTC, yihau commented
Thank you for asking! yeah, I forgot to ping you guys again. this PR is ready for another look 👀

2023-04-20 19:24 UTC, yihau commented on .buildkite/scripts/build-stable.test.sh
> +want=$(cat <<EOF
yeah! it looks so good! fixed [105db43](https://github.com/solana-labs/solana/pull/31151/commits/105db43f394ff1d76a471027f05ea99e992cc8af)

2023-04-20 19:24 UTC, yihau commented on .buildkite/scripts/common.sh
> +  cat <<EOF | indent | sed '/EMPTY_LINE/d'
oh. the EMPTY_LINE is not the real EMPTY_LINE. it is a denote for me to remove some unset attributes. I try to rename it here [453b9c3](https://github.com/solana-labs/solana/pull/31151/commits/453b9c33c7362a0f59bd6368a19d2cf02413a3e9)

2023-04-20 19:24 UTC, yihau commented on ci/stable/run-partition.sh
> +N=${1:-"$BUILDKITE_PARALLEL_JOB"} # BUILDKITE_PARALLEL_JOB from 0 to (BUILDKITE_PARALLEL_JOB_COUNT - 1)
sure! 
rename N => INDEX [be33cc9](https://github.com/solana-labs/solana/pull/31151/commits/be33cc9276466e6f6a047ad8d9a637ca6758afe9)
rename M => LIMIT [bc38a00](https://github.com/solana-labs/solana/pull/31151/commits/bc38a0047a3786e48d8255f41571bebd9a728046)

2023-04-20 19:24 UTC, yihau commented on ci/stable/run-partition.sh
> +fi
you're the king 👑 this way is so awesome! [ef9ae51](https://github.com/solana-labs/solana/pull/31151/commits/ef9ae51848a8b924d69c37d8dd345ba99af3f90c)

2023-04-20 23:16 UTC, t-nelson commented on .buildkite/scripts/common.sh
> +  cat <<EOF | indent | sed '/EMPTY_LINE/d'
oh i thought it was to work around yaml's stupid assumptions about empty lines 😅

2023-04-20 23:21 UTC, t-nelson approved these changes
:shipit:

2023-04-21 06:51 UTC, merged