bump tempfile to 3.4.0 (#30727)
solana-labs/solana pull request #31563
Opened 2023-05-09 22:15 UTC by brooksprumo

#### Problem

The `remove_dir_all` crate has a rustsec advisory. See original PR #30727 for more context.

#### Summary of Changes

Manual backport of #30727 by cherry-picking commit `c0887d31928888568dc646aa3d54d4bde8547054` from https://github.com/solana-labs/solana/pull/31009.

Note: If looking at this PR in the future at it appears as if the CI didn't "really" run, please note that I did manually push a change (commit 2) to trigger a full CI. Once it completed successfully, I removed that change (commit 3).

2023-05-10 07:54 UTC, yihau commented
I think we can add a small change to one of these files
https://github.com/solana-labs/solana/blob/8e9b064ab37a475b99f75f71cda7cefaa44e0658/ci/buildkite-pipeline.sh#L35-L37

it will trigger everything up!

2023-05-10 16:00 UTC, yihau commented
I found the running time of downstream project tests are very close 30mins in the last few times
<img width="1049" alt="Screenshot 2023-05-10 at 11 54 52 PM" src="https://github.com/solana-labs/solana/assets/8209234/8c40ca22-0fd4-4c81-9090-8e4d2160257e">

maybe we can also bump downsteam project tests's timeout to 40 mins in this same PR 🤔 
https://github.com/solana-labs/solana/blob/0a62a139fbb7c23d815f2b09fe86acbf981fe1ff/ci/buildkite-pipeline.sh#L242

2023-05-10 19:58 UTC, t-nelson commented
> I think we can add a small change to one of these files
> 
> https://github.com/solana-labs/solana/blob/8e9b064ab37a475b99f75f71cda7cefaa44e0658/ci/buildkite-pipeline.sh#L35-L37
> 
> it will trigger everything up!

shouldn't the Cargo.lock changes have triggered stable*/local-cluster*/coverage?

2023-05-10 20:00 UTC, t-nelson commented
> maybe we can also bump downsteam project tests's timeout to 40 mins in this same PR

prefer it at least be a separate commit for revertability's sake

2023-05-10 20:01 UTC, t-nelson requested changes

2023-05-10 20:01 UTC, t-nelson commented on ci/buildkite-pipeline.sh
> +# bprumo: edit to trigger full CI
drop since ci's green?

2023-05-10 22:23 UTC, mvines commented
This advisory doesn't seem to be severe enough to warrant a backport, that it's fixed in master/1.16 seems sufficient no? I

2023-05-11 03:50 UTC, yihau commented
just found the ci37 only takes 27 mins to finish downstreams project test (https://buildkite.com/solana-labs/solana/builds/95310#01880656-b85c-445b-a07b-ab2f15c56b02) and it make me recall something. I will check those ci agents first.

2023-05-11 04:19 UTC, yihau commented
> shouldn't the Cargo.lock changes have triggered stable*/local-cluster*/coverage?

yeah... just check the code and logs. I found ci pipeline thought this PR was an version bumping PR. will discuss with Will

the log
```
fatal: ambiguous argument 'v1.14..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
optional_old_version_number: -><-
new_version_number: ->1.14.18<-
fatal: ambiguous argument 'v1.14..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
diff_other_than_version_bump: -><-
Diff only contains version bump.
```

2023-05-12 04:51 UTC, t-nelson commented
> This advisory doesn't seem to be severe enough to warrant a backport, that it's fixed in master/1.16 seems sufficient no?

may as well work out whatever ci bug it's triggering

2023-05-15 13:00 UTC, closed without merging