check simple vote could have 1 or 2 signatures when creating sanitized transaction
solana-labs/solana pull request #31807
Opened 2023-05-24 22:20 UTC by taozhu-chicago

#### Problem
When replay stage flags simple vote transaction, it should check number of signatures as banking stage does [here](https://github.com/solana-labs/solana/blob/master/perf/src/sigverify.rs#L355-L359). 

#### Summary of Changes
- add tests
- add signature count check

Fixes #

2023-05-24 23:13 UTC, apfitzge requested changes
Thanks for the fix, gets these 2 checks to be consistent.

1 typo suggestion & a question about tests.

More high-level, I'm trying to think of a better way, since this still is open to inconsistency if one of the 2 impls changes. They do not directly share a data type, one is packet vs sanitized message, so this is tricky.

2023-05-24 23:13 UTC, apfitzge commented on perf/src/sigverify.rs
> +        // single legacy vote tx with extra (invalaid) signature is not
typo:
```suggestion
        // single legacy vote tx with extra (invalid) signature is not
```

2023-05-24 23:13 UTC, apfitzge commented on sdk/src/transaction/sanitized.rs
> +    fn test_try_create_simple_vote_tx() {
`is_simple_vote_tx` is an optional argument to the `try_create` fn.

Logically, these shouldn't ever be different. But the behavior is currently the passed value takes precedence.

Should the test(s) make sure that is the case?

2023-05-25 15:59 UTC, taozhu-chicago commented
> More high-level, I'm trying to think of a better way, since this still is open to inconsistency if one of the 2 impls changes. They do not directly share a data type, one is packet vs sanitized message, so this is tricky.

was thinking if `try_create()` can take `bool` instead of `Option<bool>` when creating from unsanitized versioned transaction. Looks like only few places (rpc.rs and bank.rs) actually used `None`. Maybe it is possible, leaving it to another time.

2023-05-25 16:13 UTC, apfitzge approved these changes
lgtm

2023-05-25 20:45 UTC, merged