replay: only vote on blocks with full last fec set
solana-labs/solana pull request #34294
Opened 2023-12-01 00:21 UTC by AshwinSekar

#### Problem

#### Summary of Changes

Fixes #

2023-12-01 21:41 UTC, t-nelson commented on core/src/replay_stage.rs
> +                // it as duplicate, effectively removing it from fork choice.
```suggestion
                // it as invalid, effectively removing it from fork choice.
```

right? could be for reasons other than fuckery

2023-12-01 23:17 UTC, wen-coding commented on core/src/replay_stage.rs
> +                        if erasure_meta.total_shreds() >= 64 {
We should probably get this constant from somewhere else depending on how the other PR is implemented.

2023-12-01 23:17 UTC, wen-coding commented on core/src/replay_stage.rs
> +
Add a test somewhere?

2023-12-06 17:27 UTC, AshwinSekar commented
should be merged after https://github.com/solana-labs/solana/pull/34330

2023-12-06 18:32 UTC, behzadnouri requested changes

2023-12-06 18:34 UTC, behzadnouri commented on core/src/replay_stage.rs
> +                        u32::try_from(last_shred_index).expect("LAST_SHRED_IN_SLOT should be u32"),
This does not look right. Are you using this as the `fec_set_index`?

2023-12-06 19:11 UTC, AshwinSekar commented on core/src/replay_stage.rs
> +                // it as invalid, effectively removing it from fork choice.
why? there is no bank hash change

2023-12-06 19:33 UTC, AshwinSekar commented on core/src/replay_stage.rs
> +                // it as invalid, effectively removing it from fork choice.
fair point 😅  - that specific scenario will work but 50/50 will kill us 
will add a feature gate

2024-01-12 08:04 UTC, closed without merging