Backport docs migration
solana-labs/solana pull request #34758
Opened 2024-01-11 21:51 UTC by willhickey

#### Problem
Docs are deployed from the beta branch. The docs migration is incomplete until Nick's changes are applied to beta.

#### Summary of Changes
Backport:
#34096
#34403
#34565

Fixed merge conflicts. For most merge conflicts I kept the v1.17 version but kept the links that were updated in #34380. I think this is the correct behavior but since the channels will be advancing when mainnet-beta adopts v1.17 (hopefully within 2 weeks) any mistakes will be irrelevant soon.

2024-01-19 19:07 UTC, nickfrosty commented on docs/src/developing/on-chain-programs/developing-rust.md
> +  [Stack](https://docs.solana.com/developing/on-chain-programs/faq#stack).
This should be:
```
[Stack](https://solana.com/docs/programs/faq#stack).
```

2024-01-24 17:21 UTC, nickfrosty requested changes
I noticed 2 files did not get removed with this backport

2024-01-24 17:21 UTC, nickfrosty commented on docs/src/developing/on-chain-programs/developing-rust.md
This file should be deleted per https://github.com/solana-labs/solana/commit/676e80c80a914c6f41a4f5d12f419d35a8047dd8

2024-01-24 17:21 UTC, nickfrosty commented on docs/src/developing/versioned-transactions.md
This file should be deleted per https://github.com/solana-labs/solana/commit/676e80c80a914c6f41a4f5d12f419d35a8047dd8

2024-01-31 15:54 UTC, closed without merging

2024-02-01 21:36 UTC, willhickey commented
Since the release channels have advanced we no longer need this PR. The changes in this PR were merged to master before v1.18 was branched. Now that v1.18 is the beta branch it will feed https://docs.solanalabs.com/. The docs in v1.17 don't get published anywhere.